version: "3.8"
services:
  app:
    image: lscr.io/linuxserver/unifi-network-application:8.0.28
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Maceio
      - MONGO_USER=
      - MONGO_PASS=
      - MONGO_HOST=unifi-network_db
      - MONGO_PORT=27017
      - MONGO_DBNAME=
   #   - MEM_LIMIT=1024 #optional
   #   - MEM_STARTUP=1024 #optional
   #   - MONGO_TLS= #optional
   #   - MONGO_AUTHSOURCE= #optional
    volumes:
      - ./$(pwd):/config
    networks:
      - unifi-net
    # ports:
      # - 8443:8443
      # - 3478:3478/udp
      # - 10001:10001/udp
      # - 8080:8080
      # - 1900:1900/udp #optional
      # - 8843:8843 #optional
      # - 8880:8880 #optional
      # - 6789:6789 #optional
      # - 5514:5514/udp #optional
    healthcheck:
      test: [ 'CMD', 'curl', '-fsI', 'http://localhost:8080' ]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 10s
    deploy:
          mode: global
          restart_policy:
            condition: on-failure
            delay: 5s 
            max_attempts: 5
            window: 10s

  db:
    image: docker.io/mongo:4.4
    volumes:
      - ./$(pwd):/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - unifi-net
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 10s

networks:
  unifi-net:
    name: unifi-net
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/28
